---
- name: Install ansible
  yum: name=ansible state=latest
  tags: ansible

- name: Check ansible version
  command: ansible --version
  register: ansible
  tags: ansible

- debug: 
    var: ansible
  tags: ansible

...

